name: Build and Release Docker Image

on:
  release:
    types:
      published

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        run: |
          docker login --username blue-core-lod --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build --tag ghcr.io/blue-core-lod/sinopia:latest --build-arg KEYCLOAK_URL=${{ vars.KEYCLOAK_URL }} --build-arg SINOPIA_URI=${{ vars.SINOPIA_URI }} . 
          docker push ghcr.io/blue-core-lod/sinopia:latest
